메인판 음식 및 나무 얻기 행동 라운드 로직 추가
ERICA-SE-team3/Argricola-Unity pull request #29
Opened 2023-06-06 15:05 UTC by hazzun

unit test 코드는 빼야하나요??

2023-06-07 05:41 UTC, Junhyung-Choi commented
빼주시면 좋을것 같아요 @hazzun

2023-06-07 15:13 UTC, hazzun commented
최신버전 컨플릭트 해결 및 테스트코드 삭제했습니다!

2023-06-07 23:56 UTC, Junhyung-Choi requested changes
수정 내역들 고쳐주시고 필요 없는 파일들 지워서 다시 한번만 커밋해주세요!

2023-06-07 23:56 UTC, Junhyung-Choi commented on Assets/02. Scripts/03. MainAction/01. MainDefaultAction/MainActCopse.cs
[누적카드들에 대해]
누적되어 있는 것들을 해당 수정된 변수들에 저장하는 것처럼 보이는데
한번에 몇개를 누적시키는지는 어디서 관리하나요?

2023-06-07 23:56 UTC, Junhyung-Choi commented on Assets/02. Scripts/05. GameManager/ResourceManager.cs
@ernati 이미 말씀드렸지만 주석으로 에러가 뜨길래 단순 반복성으로 여기에서도 알려드립니당.
에디터 전반적으로 파일 형식 UTF-8로 바꿔주세욥!

@hazzun 은 옆에 있는 주석 확인해서 한글로 바꿔서 한번만 다시 커밋해줄 수 있나요?

2023-06-07 23:56 UTC, Junhyung-Choi commented on Assets/InitTestScene638216113861345980.unity
어떤 파일일까요 이건? 의미 없으면 지워주세요!

2023-06-08 02:27 UTC, hazzun commented on Assets/02. Scripts/03. MainAction/01. MainDefaultAction/MainActCopse.cs
저도 그 부분을 고민해봤는데 GameManager 스크립트의 PreRound 단계에서 누적카드들에 대한 처리를 진행해주는게 맞지 않나 싶은 생각이 들었습니다!

2023-06-08 02:28 UTC, hazzun commented on Assets/InitTestScene638216113861345980.unity
네에

2023-06-08 02:32 UTC, ernati commented on Assets/02. Scripts/03. MainAction/01. MainDefaultAction/MainActCopse.cs
GameManager에 구현되어있습니다!
stack이 적용되 메인보드판 행동 카드가 총 13개라 각각 행동의 이름을 따서 stackBehavior라고 enum으로 해두었고, 그걸 이용해서 stackOfRoundCard array에 stack 값을 저장합니다!
Onclick()을 하면 stack이 0이 되고, preRound()에선 모든 스택값을 일괄적으로 1씩 늘립니다.

아마 제가 작성한 코드들이 주석이 다 깨져서.... ㅎ....

2023-06-08 02:33 UTC, ernati commented on Assets/02. Scripts/03. MainAction/01. MainDefaultAction/MainActCopse.cs
테스트할 때 이미 다 스택된 만큼 얻으면서 턴 진행되게 기능 구현된 상태입니다.

2023-06-08 02:43 UTC, Junhyung-Choi commented on Assets/02. Scripts/03. MainAction/01. MainDefaultAction/MainActCopse.cs
Enum은 보이는데, 각 행동별로 몇개씩 스택되는지는 안보이는거 같은데용...? 스택이 몇번 되었는지는 알 수 있을꺼 같은데 각 행동마다 한번에 몇개가 스택되는지는 다르지 않나용?

2023-06-08 02:47 UTC, ernati commented on Assets/02. Scripts/03. MainAction/01. MainDefaultAction/MainActCopse.cs
아! 그건 그래서 Onclick() 쪽에 자율적으로 부여했습니다!
GameManager는 stack만 관리하고, Onclick()에서 각 행동마다 stack당 2개라면 stack * 2 이렇게 해서 자원을 늘리도록 했습니다!
그 부분을 변수로 안하고, addResource 쪽에 그냥 stack * 2 식으로 써넣다 보니 보기가 쉽지 않았겠네요 죄송...

....그런데 생각해보니 1라운드부터 일괄적으로 늘리게 돼면 뒷부분 라운드 카드들의 stack도 초반부터 일괄적으로 쌓이게 되겠네요. 그부분 수정하겠습니다.

2023-06-09 14:34 UTC, merged