직업 카드 8개 추가 및 교습 행동 구현, encoding 형식 변경
ERICA-SE-team3/Argricola-Unity pull request #33
Opened 2023-06-08 07:42 UTC by ernati

- 플레이어에게 할당된 직업 카드 목록

Player 0 : magician ( 마술사 ), wood cutter ( 나무꾼 )

Player 1 :  vegetable seller ( 채소 장수 ) , wood picker( 장작 채집자 )

Player 2 : wall master ( 초벽질공 ), stone cutter ( 돌 자르는 사람 )

Player 3 : organic farmer ( 유기 농부 ), pig breeder ( 돼지 사육사 )

- 교습에 들어가면 위에 써져 있는 순서대로 카드 획득

- 이 중 구현된 부분
    - 자원 단순획득과 관련된 부분
    - 마술사, 나무꾼, 채소 장수

- 마술사 → 유랑극단 → MainActTravelingTheater.cs
    - 마술사 카드를 보유 중이라면 나무 1개, 곡식 1개 추가
    - 확인 메시지 출력
- 나무꾼 - 나무 누적 칸을 이용할 때, 나무 1개를 추가로 가져옵니다.
    - 덤불 → MainActCopse.cs
    - 수풀 → MainActGrove.cs
    - 숲 → MainActForest.cs
- vegetable seller ( 채소 장수 ) - 곡식 종자 칸을 이용할 때 , 채소 1개를 추가로 가져옵니다.
    - 곡식 종자 ( MainActGranSeed.cs )

- 인코딩 변경해야할 파일 모두 변경 완료

2023-06-08 08:00 UTC, Junhyung-Choi requested changes
리뷰했습니다~

2023-06-08 08:00 UTC, Junhyung-Choi commented on Assets/02. Scripts/03. MainAction/01. MainDefaultAction/MainActCopse.cs
GetCurentPlayerId로 작성하고 있는데 어짜피 액션은 실제 로컬에서 사용하는 플레이어만 사용할 예정이니까 CurrentPlayerId보다 실제 플레이어 아이디를 넣는 편이 좋을 것 같아요. 나중에 한꺼번에 리팩토링이 필요해보입니다.

2023-06-08 08:00 UTC, Junhyung-Choi commented on Assets/02. Scripts/03. MainAction/01. MainDefaultAction/MainActGrove.cs
모든 액션에 해당 형태롤 사용할거라면 오히려 ResourceManager에서 addResource 에서 카드를 처리하는건 어떨까요? 예외 상황이 있을까요?

2023-06-08 08:00 UTC, Junhyung-Choi commented on Assets/02. Scripts/05. GameManager/GameManager.cs
enum 시작명과 타입 CamelCase - 대문자로 사용해주세요.

2023-06-08 08:00 UTC, Junhyung-Choi commented on Assets/02. Scripts/05. GameManager/Player.cs
해당 카드들을 따로 나누지 말고 한 리스트로 관리하되, 특정 카드들에 번호 영역을 나누는게 좋지 않을까요?
예) 1~8 : 메인카드
9 ~ 16 : 보조카드
17 ~ 24 : 직업카드

2023-06-08 08:00 UTC, Junhyung-Choi commented on Assets/02. Scripts/05. GameManager/ResourceManager.cs
지금 확인한거긴 한데 각 자원별로 Increment를 나눈 이유가 있을까요?

2023-06-08 08:00 UTC, Junhyung-Choi commented on Assets/03. Assets/04. Image/카드/직업카드/magician.jpg
이름들 CamelCase로 바꿔주세요. [이하 사진 전부]

2023-06-08 08:00 UTC, Junhyung-Choi commented on Assets/02. Scripts/03. MainAction/01. MainDefaultAction/MainActLessonFood2.cs
Cards Enum을 굳이 GameManger의 하위 클래스로 둘 필요가 없어보이네요. 바깥으로 빼죠

2023-06-08 08:00 UTC, Junhyung-Choi commented on Assets/02. Scripts/03. MainAction/01. MainDefaultAction/MainActLessonFood2.cs
한명의 플레이어만이 이 함수를 사용합니다. 테스트 코드는 따로 Test 폴더 안에 작성하시고 실 사용 코드를 남겨주세요.
기능 테스팅이 필요한 상황이라면 함수로 영역을 분리해주세요

2023-06-08 08:00 UTC, Junhyung-Choi commented on Assets/02. Scripts/03. MainAction/01. MainDefaultAction/mainActLessonFood1.cs
2와 마찬가지

2023-06-08 09:17 UTC, ernati commented on Assets/02. Scripts/05. GameManager/GameManager.cs
넵! 수정해서 적용하겠습니다.

2023-06-08 09:19 UTC, ernati commented on Assets/02. Scripts/05. GameManager/Player.cs
교습을 할 때, List에 카드가 있는지 여부를 Contain()으로 check했는데, 이 때 한 List를 사용하게 돼면, 좀 애매해서 분리를 했었습니다!
다만 저도 리스트 하나로 관리를 하면 편하기에 한번 고려해보겠습니다!

2023-06-08 09:19 UTC, ernati commented on Assets/02. Scripts/05. GameManager/ResourceManager.cs
이거슨 그냥 my routine...

2023-06-08 09:20 UTC, ernati commented on Assets/03. Assets/04. Image/카드/직업카드/magician.jpg
녜 수정할게요!

2023-06-08 09:20 UTC, ernati commented on Assets/02. Scripts/03. MainAction/01. MainDefaultAction/MainActLessonFood2.cs
Card.cs 만들어서 쓰겠습니당!

2023-06-08 11:08 UTC, ernati commented on Assets/02. Scripts/03. MainAction/01. MainDefaultAction/MainActGrove.cs
어떤 카드의 추가효과로 나무를 얻는 경우에 
나무꾼 카드를 가지고 있을 경우...?  와 같은 비슷한 경우에 문제가 생길 것 같습니당~!

2023-06-10 13:47 UTC, Junhyung-Choi reviewed
코멘트 받아주세용

2023-06-10 13:47 UTC, Junhyung-Choi commented on Assets/02. Scripts/00. Tests/TestMainActLessonFood1.cs
테스팅 코드 이렇게 작성하는거 아닌데 일단 넘어갈께요.
나중에 씬에서 적용시키는 코드 있으면 없애주세요.

2023-06-10 13:47 UTC, Junhyung-Choi commented on Assets/02. Scripts/02. Game/PlayerBoard.cs
테스팅코드들은 왜만든건가요?

2023-06-10 13:47 UTC, Junhyung-Choi commented on Assets/02. Scripts/03. MainAction/01. MainDefaultAction/MainActDirtPit.cs
OnClick 분리한 이유가 있나요?

2023-06-10 13:47 UTC, Junhyung-Choi commented on Assets/02. Scripts/03. MainAction/02. MainRoundAction/GrainUtilizationRoundAct.cs
큐 형식으로 바꿔야할거같은데 확인 부탁

2023-06-10 13:53 UTC, ernati commented on Assets/02. Scripts/03. MainAction/02. MainRoundAction/GrainUtilizationRoundAct.cs
아 이거 그래서 하준님이 Queue형식으로 라운드 행동 작업하시는 중이라 안건드렸습니당!
하준님이 Queue로 전부 바꾸는 작업끝나면 모두 일괄적으로 card 제가 적용할 계획입니당!

2023-06-10 13:53 UTC, ernati commented on Assets/02. Scripts/03. MainAction/01. MainDefaultAction/MainActDirtPit.cs
....Test....용인데.... 형식 파괴자 윤재현은 프로젝트 끝나고 도게자 박겠습니다...

2023-06-10 15:49 UTC, closed without merging